# Generated by Django 4.2.6 on 2023-12-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(default='Công ty điện lực Quảng Trị', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('serial', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('pack', models.CharField(blank=True, max_length=255, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('date_connect', models.DateField(blank=True, null=True)),
                ('date_join', models.DateField(blank=True, null=True)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_use', models.DateField(blank=True, null=True)),
                ('data', models.IntegerField(blank=True, null=True)),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phone')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AddField(
            model_name='phone',
            name='system_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.system'),
        ),
    ]
