# Generated by Django 4.2.6 on 2023-12-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('network_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('network', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='phoneitem',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.phone'),
        ),
        migrations.AddField(
            model_name='phone',
            name='network_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.network'),
        ),
    ]
