# Generated by Django 4.2.6 on 2023-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_network_alter_phoneitem_serial_phone_network_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
